-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 00:31:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wpiatmdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wpiatmdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wpiatmdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `wpiatmdb` ;

-- -----------------------------------------------------
-- Table `wpiatmdb`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wpiatmdb`.`administrators` (
  `usertype` VARCHAR(30) NOT NULL,
  `userid` VARCHAR(30) NOT NULL,
  `userpin` VARCHAR(30) NULL DEFAULT NULL,
  `administratornumber` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`usertype`, `userid`),
  INDEX `administratornumber` (`administratornumber` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `wpiatmdb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wpiatmdb`.`customers` (
  `usertype` VARCHAR(30) NULL DEFAULT NULL,
  `userid` VARCHAR(30) NOT NULL,
  `userpin` VARCHAR(30) NULL DEFAULT NULL,
  `holdingcompany` VARCHAR(30) NULL DEFAULT NULL,
  `startingbalance` VARCHAR(30) NULL DEFAULT NULL,
  `userstatus` VARCHAR(30) NULL DEFAULT NULL,
  `accountnumber` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `transactioninfo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`userid`),
  INDEX `accountnumber` (`accountnumber` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
